version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/demo-docker-image:$CIRCLE_SHA1 .
            docker tag $DOCKER_USERNAME/demo-docker-image:$CIRCLE_SHA1 $DOCKER_USERNAME/demo-docker-image:latest
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_USERNAME/demo-docker-image:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/demo-docker-image:latest
workflows:
  build:
    jobs:
      - build